{% set name = "yaspin" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yaspin-{{ version }}.tar.gz
  sha256: 0498039b3e110f53824417a9f59418a20843e8752b8b15c26bb81a659d4aec5c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python !=3.0,!=3.1,!=3.2,!=3.3,!=3.4
    - poetry
  run:
    - python !=3.0,!=3.1,!=3.2,!=3.3,!=3.4

test:
  imports:
    - yaspin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pavdmyt/yaspin
  summary: Yet Another Terminal Spinner
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ickc
