{% set name = "yaspin" %}
{% set version = "1.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yaspin-{{ version }}.tar.gz
  sha256: d8fc9bc1c8be225877ea6e2e08fec96c2b52e233525a5c40b92d373f015439c6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python !=3.0,!=3.1,!=3.2,!=3.3,!=3.4
    - poetry
  run:
    - python !=3.0,!=3.1,!=3.2,!=3.3,!=3.4

test:
  imports:
    - yaspin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pavdmyt/yaspin
  summary: Yet Another Terminal Spinner
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ickc
